services:
  stt-service:
    env_file: ../env/dev.env

  tts-service:
    env_file: ../env/dev.env

  chat-service:
    env_file: ../env/dev.env

  document-service:
    env_file: ../env/dev.env

  quiz-service:
    env_file: ../env/dev.env

  api-gateway:
    env_file: ../env/dev.env
